### PR TITLE
fix: remove duplicate refresh for all connections

### LINKED ISSUE #525: Connector starts duplicate refresh operations
### Bug Description

While adding debug logging, I discovered the Go Connector is initiating duplicate refresh operations on every connection attempt, given how we're not initializing the TLS leaf certificate correctly.

### Example code (or command)

_No response_

### Stacktrace

_No response_

### Steps to reproduce?

n/a

### Environment

n/a

### Additional Details

_No response_

### PR DESCRIPTION
**Pull request by enocom**
When we added a check to validate certificates on all new connections
[1], we also inadverantly caused each connection to trigger a duplicate
and blocking refresh operation with the following lines:

if c.Certificates[0].Leaf == nil {
	return true
}

When the tls.Config is created in refresh.go, it configures a client
certificate chain and adds the CA cert as a Root CA. However, the client
certificate chian is created with tls.X509KeyPair which explicitly
states:

"On successful return, Certificate.Leaf will be nil because the parsed
form of the certificate is not retained." [2]

As a result, the nil check above was always triggered and thereby
causing a duplicate refresh operation. An immediate fix to this
situation is to set the leaf certificate, which is what this commit
does. In fact, we're already parsing the leaf certificate to determine
its expiration and saving the parsed certificate has a performance
benefit:

[The Leaf certificate] may be initialized using x509.ParseCertificate to
reduce per-handshake processing. [3]

[1]: https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/456
[2]: https://pkg.go.dev/crypto/tls#X509KeyPair
[3]: https://pkg.go.dev/crypto/tls#Certificate.Leaf

Fixes #525

### CODE REVIEW

File: internal/alloydb/refresh.go [hunk 1]
```diff
@@ -177,6 +177,9 @@ func fetchEphemeralCert(
 			err,
 		)
 	}
+	// Save the parsed certificate as the leaf certificate, to avoid additional
+	// parsing costs as part of the TLS connection.
+	cert.Leaf = clientCert
```
Comment (jackwotherspoon) [inline internal/alloydb/refresh.go:182]: does purely setting this reduce the parsing costs? or do we need to update somewhere else to access it?

**Review by jackwotherspoon — APPROVED** [review]

File: internal/alloydb/refresh.go (hunk 1 above)
Comment (enocom) [reply internal/alloydb/refresh.go:182]: This is it. Since we're parsing the certificate above we just need to set this. For now, we're already depending on this to be set correctly to ensure we can read the expiration in dialer.go. I have a refactor PR that will remove the tight coupling between this code and dialer that is coming up next.
