### PR TITLE
fix: reduce the number of memory allocations and latency overhead

### LINKED ISSUE #684: Reduce heap allocation and latency in instrumented conn
See https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/983.

### PR DESCRIPTION
**Pull request by nancynh**
Fixes #684 - a port of the same change in CloudSQL's https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/983. Small difference here is opting to use `(*atomic.Int64) Add` and `(*atomic.Int64) Swap` instead to avoid bugs with 32-bit platforms ([ref](https://pkg.go.dev/sync/atomic#pkg-note-BUG))

### CODE REVIEW

File: dialer.go [hunk 1]
```diff
@@ -625,14 +631,18 @@ type instrumentedConn struct {
...
 }
 
 // Read delegates to the underlying net.Conn interface and records number of
 // bytes read.
 func (i *instrumentedConn) Read(b []byte) (int, error) {
 	bytesRead, err := i.Conn.Read(b)
 	if err == nil {
-		go tel.RecordBytesReceived(context.Background(), int64(bytesRead), i.instance, i.dialerID)
+		i.bytesRead.Add(int64(bytesRead))
 		go i.metricRecorder.RecordBytesRxCount(context.Background(), int64(bytesRead), i.attrs)
```
Comment (enocom) [inline dialer.go:646]: This will need to move into the report goroutine too. Same with RecordBytesTxCount too.

Comment (nancynh) [reply dialer.go]: Done

**Review by enocom — APPROVED** [review]
Thank you!
